name: My first workflow
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: "Welcome"
          run: echo "My first workflow"
        
        - name: "List"
          run: ls
        
        - name: "Read the file"
          run: cat README.md